name: Tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # We test on:
        # - Earliest supported version
        # - Latest version of each major
        # - JRuby
        ruby: [ '2.4', '2.7', '3.1', 'jruby' ]
    name: ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake